### PR TITLE
Update documentation for 1.0.0

### PR DESCRIPTION
**Pull request by JohnPaton**

### CODE REVIEW

**Review by avaldebe — DISMISSED** [review]
LGTM 🚀

**Comment by JohnPaton** [comment]
haha, it is not in fact good, forgot to make this a draft - will ping when it's ready!

**Comment by JohnPaton** [comment]
Alright it looks good to go, check the [preview](https://airbase--64.org.readthedocs.build/en/64/index.html) if you want!

**Review by avaldebe — APPROVED** [review]
ready to merge

**Pull request merged**
