### PR TITLE
support Python 3.11

### PR DESCRIPTION
**Pull request by avaldebe**

### CODE REVIEW

**Comment by avaldebe** [comment]
The cleanest way to deal with the `importlib.resources` deprecation warning introduced on Python 3.11 was to import `importlib_resources` on previous versions of Python.

**Comment by JohnPaton** [comment]
LGTM, thanks!

**Comment by JohnPaton** [comment]
Once master pipeline passes let's release 0.6.0 with 3.11 support

**Comment by avaldebe** [comment]
that was easy! 📦 🐍 3.11 done 🚀 🎆

**Comment by JohnPaton** [comment]
Awesome, good work!

They are actually only verified because I created them through the GitHub UI - easy peasy

**Pull request merged**
